### ISSUE TITLE
Directed Graph and Breadth First Search in Golang

### ISSUE THREAD

**Issue by Ch3ck** [Ch3ck/algo#13]

**Comment by anthonyabeo** [comment]
Hello @Ch3ck,

I will like to work on this.
BTW, which implementation of the directed graph is expected? Adjacency List or Adjacency Map?

**Comment by Ch3ck** [comment]
start with an adjacency list @anthonyabeo

**Comment by anthonyabeo** [comment]
noted, @Ch3ck .

**Comment by anthonyabeo** [comment]
@Ch3ck it seems there already is an implementation of a directed graph; Inside the 'graph' package. Kindly check that to ensure that work on something that already exists. Standing by for confirmation.

**Comment by anthonyabeo** [comment]
@Ch3ck i just submitted a PR. 
Standing by to discuss it.
