### ISSUE TITLE
Go fmt issues

### ISSUE THREAD

**Issue by Ch3ck** [Ch3ck/AlGo#43]
Gofmt formats Go programs. We run gofmt -s on your code, where -s is for the "simplify" command
Algo/rabinkarp/rabinkarp_test.go
Line 1: warning: file is not gofmted with -s (gofmt)
Algo/insertsort/insertsort_test.go
Line 1: warning: file is not gofmted with -s (gofmt)
Algo/rabinkarp/rabinkarp.go
Line 1: warning: file is not gofmted with -s (gofmt)

**Comment by arxdsilva** [comment]
is this still on?
