### ISSUE TITLE
golint

### ISSUE THREAD

**Issue by ch3ck** [ch3ck/algo#45]
Golint is a linter for Go source code.
Algo/convexHull/convexHull.go
Line 8: warning: exported type Point should have comment or be unexported (golint)
Line 12: warning: exported type Points should have comment or be unexported (golint)
Algo/stack/stack.go
Line 27: warning: comment on exported method Stack.Len should be of the form "Len ..." (golint)
Algo/rabinkarp/rabinkarp.go
Line 57: warning: exported function Hash should have comment or be unexported (golint)
Line 65: warning: exported function HashPatterns should have comment or be unexported (golint)
Line 79: warning: exported function MinLen should have comment or be unexported (golint)
Algo/insertsort/insertsort.go
Line 3: warning: exported function Swap should have comment or be unexported (golint)
Line 9: warning: exported function InsertSort should have comment or be unexported (golint)
Algo/insertsort/insertsort_test.go
Line 10: warning: don't use underscores in Go names; struct field unsorted_slice should be unsortedSlice (golint)
Line 11: warning: don't use underscores in Go names; struct field sorted_slice should be sortedSlice (golint)
Algo/qsort/qsort.go
Line 6: warning: package comment should be of the form "Package qsort ..." (golint)
Line 6: warning: package comment should not have leading space (golint)
Line 11: warning: comment on exported function Qsort should be of the form "Qsort ..." (golint)
Algo/qsort/qsort_test.go
Line 13: warning: don't use underscores in Go names; struct field unsorted_slice should be unsortedSlice (golint)
Line 14: warning: don't use underscores in Go names; struct field sorted_slice should be sortedSlice (golint)

**Comment by crazcalm** [comment]
@Ch3ck Do you mind if I take this issue?

**Comment by Ch3ck** [comment]
By all mean @crazcalm fix it.

**Comment by crazcalm** [comment]
@Ch3ck I created a PR https://github.com/Ch3ck/AlGo/pull/48. The Travis CI check failed... Should I be worried about that?
