### ISSUE TITLE
Misspell issues in code

### ISSUE THREAD

**Issue by Ch3ck** [Ch3ck/AlGo#46]
Misspell Finds commonly misspelled English words
Algo/queuestack/stack_test.go
Line 34: warning: found "occuring" a misspelling of "occurring" (misspell)
Line 71: warning: found "occured" a misspelling of "occurred" (misspell)
Algo/rabinkarp/rabinkarp.go
Line 22: warning: found "occurence" a misspelling of "occurrence" (misspell)
Algo/knuthMorrisPratt/knuthMorrisPratt.go
Line 1: warning: found "occurences" a misspelling of "occurrences" (misspell)
Line 5: warning: found "occurences" a misspelling of "occurrences" (misspell)
Algo/queuestack/queue_test.go
Line 34: warning: found "occuring" a misspelling of "occurring" (misspell)
Line 71: warning: found "occured" a misspelling of "occurred" (misspell)

**Comment by seancyw** [comment]
Hi, I would like to take this. :)

**Comment by Ch3ck** [comment]
@seancyw Cool, Star the repo first, fork and then Make a PR; make sure you follow the instructions in Contributing.md
