### ISSUE TITLE
Bubblesort test failing

### ISSUE THREAD

**Issue by anthonyabeo** [Ch3ck/algo#64]
The test for the bubblesort algorithm implemented in bubblesort/bubblesort_test.go is failing. This is the failing test.

--- FAIL: TestBubbleSort (0.00s)
    bubblesort_test.go:44: ERROR! Expected: [53869565043771892 327278216295208011 419486536116368092 478292018523940491 591629291660158161 637089620209289710 745913797565529122 752023583267238363 844765876686216240 844801911949832161 877898243438526380 962352279814489065 1235951969156423557 1248947886802139853 1250411451318132563 1346054179169839272 1392741588488989104 1502485539044195906 1889690910361684197 2113755922137896332 2301488955750818158 2387783153859091163 2464476033583135183 2479536531735175331 2508694526360179358 2823763818817307209 2826831562756948462 2848054462804617789 2878373336162965471 3032706688432892106 3103310900862753990 3108237542363837401 3113060502492707357 3201859879512578482 3235072086746618018 3268805855679129509 3283763650087443374 3290502868925159387 3386115355036305893 3463293267593940144 3502362782625572512 3515876857310610618 3519126916436391806 3538374564974679734 3801845893934096201 3947939694947847894 4053304216848371784 4057519091797218140 4074852610135052174 4141126573816985001 4475600347793546623 4544924005408192709 4616774575524807546 4802714051385199294 5092864841952955017 5382590036135861266 5427335742178504527 5820042179253306070 5869245081276785300 5909043311279533243 6026834734704272674 6063286229123263068 6085601919590992497 6161001777650501815 6215352726517872062 6338254959309311510 6415404711267476495 6466064872941976972 6529250035999490342 6605128170854773495 6620280236380274804 6621668130244569842 6701925676188740121 6892661516919641240 6902029020509405909 7014659597777243143 7223963853217364387 7328689391914852508 7472059465348907731 7485390727874691325 7600277364322323579 7735103018165134725 7775007378384577665 7824159090485789544 7844802260196808485 8063502634014346762 8106065328409096030 8155532924671626830 8180855146735145105 8258770950502883915 8344697809072524593 8432075160139049777 8453581750806653790 8462264414184403991 8503869084561059637 8506525599482213261 8599623643053325590 8934798893102412996 8971266663425214366 9014549318209835295] Result: [2301488955750818158 3103310900862753990 3515876857310610618 591629291660158161 2823763818817307209 1235951969156423557 1250411451318132563 4544924005408192709 637089620209289710 3386115355036305893 3463293267593940144 2508694526360179358 3268805855679129509 3801845893934096201 2464476033583135183 2848054462804617789 1392741588488989104 3502362782625572512 2387783153859091163 327278216295208011 3290502868925159387 4053304216848371784 2826831562756948462 4475600347793546623 3032706688432892106 3283763650087443374 53869565043771892 1346054179169839272 752023583267238363 1889690910361684197 478292018523940491 844801911949832161 3108237542363837401 1502485539044195906 2878373336162965471 2479536531735175331 962352279814489065 877898243438526380 844765876686216240 3201859879512578482 745913797565529122 3235072086746618018 3519126916436391806 3947939694947847894 3538374564974679734 4057519091797218140 1248947886802139853 419486536116368092 2113755922137896332 3113060502492707357 4074852610135052174 4141126573816985001 4616774575524807546 4802714051385199294 5092864841952955017 5382590036135861266 5427335742178504527 5820042179253306070 5869245081276785300 5909043311279533243 6026834734704272674 6063286229123263068 6085601919590992497 6161001777650501815 6215352726517872062 6338254959309311510 6415404711267476495 6466064872941976972 6529250035999490342 6605128170854773495 6620280236380274804 6621668130244569842 6701925676188740121 6892661516919641240 6902029020509405909 7014659597777243143 7223963853217364387 7328689391914852508 7472059465348907731 7485390727874691325 7600277364322323579 7735103018165134725 7775007378384577665 7824159090485789544 7844802260196808485 8063502634014346762 8106065328409096030 8155532924671626830 8180855146735145105 8258770950502883915 8344697809072524593 8432075160139049777 8453581750806653790 8462264414184403991 8503869084561059637 8506525599482213261 8599623643053325590 8934798893102412996 8971266663425214366 9014549318209835295]
FAIL
FAIL	algo/bubblesort	0.006s

**Comment by Ch3ck** [comment]
Do you want to fix it @anthonyabeo ?

**Comment by anthonyabeo** [comment]
Sure thing. @Ch3ck

**Comment by anthonyabeo** [comment]
@Ch3ck i have made some PR. kindly check them out at your earliest convenience.
