### ISSUE TITLE
Red Black Trees in Golang

### ISSUE THREAD

**Issue by Ch3ck** [Ch3ck/AlGo#8]

**Comment by Duxy1996** [comment]
Hi, I have been working with this kind of data structures, but I have never contributed in a project. I you want, I would like to do this issue. thanks 
Duxy1996

**Comment by dgisser** [comment]
https://github.com/sakeven/RbTree/blob/master/rbtree.go

**Comment by Ch3ck** [comment]
@dgisser guess you should make a PR then

**Comment by alimasyhur** [comment]
I added red black tree implementation on the btree directory.
Kindly check it out

**Comment by Ch3ck** [comment]
Awesome, let me merge that
